################################################################################
#
# ingenic-flash
#
################################################################################

INGENIC_FLASH_VERSION = 1.0
# Point at wherever you keep the embedded/ sources. For a local checkout use
# the override mechanism (see below) or set these to your git/tarball remote.
INGENIC_FLASH_SITE = $(call github,your-org,ingenic-flash-tool,v$(INGENIC_FLASH_VERSION))
INGENIC_FLASH_SUBDIR = embedded
INGENIC_FLASH_LICENSE = MIT
INGENIC_FLASH_LICENSE_FILES = LICENSE
INGENIC_FLASH_DEPENDENCIES = libusb zlib host-pkgconf

# firmware_blob.h is committed in the tree (generated by gen_blob.py), so the
# target build needs no Python. The Makefile uses pkg-config + $(CC), which
# Buildroot points at the cross toolchain automatically.
define INGENIC_FLASH_BUILD_CMDS
	$(MAKE) $(TARGET_CONFIGURE_OPTS) PKG_CONFIG="$(PKG_CONFIG_HOST_BINARY)" \
		-C $(@D)/$(INGENIC_FLASH_SUBDIR) ingenic_flash
endef

define INGENIC_FLASH_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/$(INGENIC_FLASH_SUBDIR)/ingenic_flash \
		$(TARGET_DIR)/usr/bin/ingenic_flash
endef

$(eval $(generic-package))
