#!/usr/bin/env python3
"""Generate firmware_blob.h for the compact C flasher.

Embeds the prj008 (T33ZN board) firmware bundle and the cfg2 payload, already
patched for the board's SPI NOR chip exactly as the Python tool would send it.
Two cfg2 variants are emitted: sector-erase (default) and chip-erase
(--erase-all), matching ingenic_flash.protocol.flash_firmware.

Run from anywhere; it imports the in-tree ingenic_flash package.

    ./.venv/bin/python embedded/gen_blob.py
"""

import sys
import zlib
from pathlib import Path

# Make the in-tree package importable without installing.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from ingenic_flash.chips import chip_by_name
from ingenic_flash.protocol import _patch_sfc_erase_mode
from ingenic_flash.spiflash_db import load_chip_db, lookup_chip, patch_cfg2

# --- Board / chip selection -------------------------------------------------
BOARD = "prj008"          # T33ZN board firmware bundle
FLASH_OPS_NOR = 0x00060000  # SPISFC | SFC_NOR

# Supported SPI NOR chips (JEDEC IDs). The tool reads the live JEDEC and picks
# the matching embedded cfg2 at runtime. With no command-line args, embed the
# ENTIRE spiflashinfo.cfg database (all vendors). To restrict to a subset:
#   python gen_blob.py 0xef7018 0xef4020
# Manufacturer IDs (JEDEC top byte) embedded by default.
KEEP_MFR = {
    0xEF,  # Winbond
    0xC8,  # GigaDevice
    0x0B,  # XTX
    0x68,  # Boya
}


def _target_jedecs() -> list[int]:
    if len(sys.argv) > 1:
        return [int(a, 0) for a in sys.argv[1:]]
    # Default: only the kept vendors. Skip malformed entries whose JEDEC
    # exceeds 24 bits (a live GET_FLASH_INFO returns 3 bytes, so those could
    # never match anyway).
    return sorted(j for j in load_chip_db()
                  if j <= 0xFFFFFF and (j >> 16) in KEEP_MFR)


TARGET_JEDECS = _target_jedecs()

FW_DIR = ROOT / "src" / "ingenic_flash" / "firmware" / BOARD


def cfg2_variants(jedec: int):
    """Return (chip, sector_erase, chip_erase) cfg2 payloads for one JEDEC."""
    base = (FW_DIR / "cfg2_bulk.bin").read_bytes()
    chip = lookup_chip(jedec)
    if chip is None:
        raise SystemExit(f"JEDEC 0x{jedec:06x} not in spiflashinfo.cfg")
    patched = patch_cfg2(base, chip)            # DB params (matches Python)
    sector = _patch_sfc_erase_mode(patched, 0)  # default: sector erase
    return chip, sector, patched                # chip-erase keeps cfg's mode


def emit_array(out, name: str, data: bytes) -> None:
    out.append(f"static const unsigned char {name}[] = {{")
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        out.append(f"    {row},")
    out.append("};")
    out.append(f"static const unsigned {name}_len = {len(data)};\n")


def main() -> int:
    board = chip_by_name("t33zn") if _has("t33zn") else chip_by_name(BOARD)

    # Pack every blob into one buffer, recording each one's (offset, len). All
    # blobs share a single zlib stream, so the 54 near-identical cfg2 configs
    # collapse to almost nothing and U-Boot compresses ~2x. The C side inflates
    # this once at startup and indexes blobs by offset.
    raw = bytearray()
    region = {}  # key -> (offset, length)

    def add(key: str, data: bytes) -> None:
        region[key] = (len(raw), len(data))
        raw.extend(data)

    add("GINFO", (FW_DIR / "ginfo.bin").read_bytes())
    add("SPL", (FW_DIR / "spl.bin").read_bytes())
    add("UBOOT", (FW_DIR / "uboot.bin").read_bytes())
    add("CFG1_EP0", (FW_DIR / "cfg1_ep0.bin").read_bytes())
    add("CFG1_BULK", (FW_DIR / "cfg1_bulk.bin").read_bytes())
    add("CFG2_EP0", (FW_DIR / "cfg2_ep0.bin").read_bytes())

    chips = []  # (jedec, name, sector_off, sector_len, chip_off, chip_len)
    for jedec in TARGET_JEDECS:
        cp, sector, chip_erase = cfg2_variants(jedec)
        s_key, c_key = f"S_{jedec:06x}", f"C_{jedec:06x}"
        add(s_key, sector)
        add(c_key, chip_erase)
        chips.append((jedec, cp.name, *region[s_key], *region[c_key]))

    packed = zlib.compress(bytes(raw), 9)

    out: list[str] = []
    out.append("/* Generated by gen_blob.py — do not edit. */")
    out.append(f"/* Board: {BOARD}  chips: "
               + ", ".join(f"0x{j:06x}({n})" for j, n, *_ in chips) + " */")
    out.append("#ifndef FIRMWARE_BLOB_H")
    out.append("#define FIRMWARE_BLOB_H\n")
    out.append("#define INGENIC_VID   0xA108")
    out.append(f"#define BOOT_PID      0x{board.usb_pid:04X}")
    out.append(f"#define GINFO_ADDR    0x{board.ginfo_addr:08X}u")
    out.append(f"#define SPL_ADDR      0x{board.spl_addr:08X}u")
    out.append(f"#define STAGE2_ADDR   0x{board.stage2_addr:08X}u")
    out.append(f"#define D2I_LEN       0x{board.d2i_len:X}u")
    out.append(f"#define FLASH_OPS_NOR 0x{FLASH_OPS_NOR:08X}u\n")

    # The single packed (zlib-compressed) firmware image.
    out.append(f"#define FW_RAW_LEN {len(raw)}u")
    emit_array(out, "fw_packed", packed)  # also emits fw_packed_len (compressed)

    # Offsets/lengths of each blob within the inflated buffer.
    for key in ("GINFO", "SPL", "UBOOT", "CFG1_EP0", "CFG1_BULK", "CFG2_EP0"):
        off, length = region[key]
        out.append(f"#define {key}_OFF {off}u")
        out.append(f"#define {key}_LEN {length}u")
    out.append("")

    # Runtime chip table: live JEDEC -> matching cfg2 payloads (by offset).
    out.append("struct nor_chip {")
    out.append("    unsigned jedec;")
    out.append("    const char *name;")
    out.append("    unsigned cfg2_sector_off, cfg2_sector_len;")
    out.append("    unsigned cfg2_chip_off,   cfg2_chip_len;")
    out.append("};")
    out.append("static const struct nor_chip nor_chips[] = {")
    for jedec, name, s_off, s_len, c_off, c_len in chips:
        out.append(f'    {{ 0x{jedec:06x}u, "{name}", '
                   f"{s_off}u, {s_len}u, {c_off}u, {c_len}u }},")
    out.append("};")
    out.append(f"static const int nor_chips_count = {len(chips)};\n")
    out.append("#endif /* FIRMWARE_BLOB_H */")

    dest = Path(__file__).resolve().parent / "firmware_blob.h"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest} ({len(chips)} chips, {len(raw)} B raw -> "
          f"{len(packed)} B packed)")
    return 0


def _has(name: str) -> bool:
    try:
        chip_by_name(name)
        return True
    except KeyError:
        return False


if __name__ == "__main__":
    raise SystemExit(main())
