#!/usr/bin/env python3
"""Generate firmware_blob.h for the compact C flasher.

Embeds the prj008 (T33ZN board) firmware bundle and the cfg2 payload, already
patched for the board's SPI NOR chip exactly as the Python tool would send it.
Two cfg2 variants are emitted: sector-erase (default) and chip-erase
(--erase-all), matching ingenic_flash.protocol.flash_firmware.

Run from anywhere; it imports the in-tree ingenic_flash package.

    ./.venv/bin/python embedded/gen_blob.py
"""

import sys
from pathlib import Path

# Make the in-tree package importable without installing.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from ingenic_flash.chips import chip_by_name
from ingenic_flash.protocol import _patch_sfc_erase_mode
from ingenic_flash.spiflash_db import load_chip_db, lookup_chip, patch_cfg2

# --- Board / chip selection -------------------------------------------------
BOARD = "prj008"          # T33ZN board firmware bundle
FLASH_OPS_NOR = 0x00060000  # SPISFC | SFC_NOR

# Supported SPI NOR chips (JEDEC IDs). The tool reads the live JEDEC and picks
# the matching embedded cfg2 at runtime. With no command-line args, embed the
# ENTIRE spiflashinfo.cfg database (all vendors). To restrict to a subset:
#   python gen_blob.py 0xef7018 0xef4020
def _target_jedecs() -> list[int]:
    if len(sys.argv) > 1:
        return [int(a, 0) for a in sys.argv[1:]]
    # Whole DB, minus malformed entries whose JEDEC exceeds 24 bits (a live
    # GET_FLASH_INFO only returns 3 bytes, so those could never match anyway).
    return sorted(j for j in load_chip_db() if j <= 0xFFFFFF)


TARGET_JEDECS = _target_jedecs()

FW_DIR = ROOT / "src" / "ingenic_flash" / "firmware" / BOARD


def cfg2_variants(jedec: int):
    """Return (chip, sector_erase, chip_erase) cfg2 payloads for one JEDEC."""
    base = (FW_DIR / "cfg2_bulk.bin").read_bytes()
    chip = lookup_chip(jedec)
    if chip is None:
        raise SystemExit(f"JEDEC 0x{jedec:06x} not in spiflashinfo.cfg")
    patched = patch_cfg2(base, chip)            # DB params (matches Python)
    sector = _patch_sfc_erase_mode(patched, 0)  # default: sector erase
    return chip, sector, patched                # chip-erase keeps cfg's mode


def emit_array(out, name: str, data: bytes) -> None:
    out.append(f"static const unsigned char {name}[] = {{")
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        out.append(f"    {row},")
    out.append("};")
    out.append(f"static const unsigned {name}_len = {len(data)};\n")


def main() -> int:
    board = chip_by_name("t33zn") if _has("t33zn") else chip_by_name(BOARD)

    # Shared blobs (same for every NOR chip on this board).
    shared = {
        "fw_ginfo":     (FW_DIR / "ginfo.bin").read_bytes(),
        "fw_spl":       (FW_DIR / "spl.bin").read_bytes(),
        "fw_uboot":     (FW_DIR / "uboot.bin").read_bytes(),
        "fw_cfg1_ep0":  (FW_DIR / "cfg1_ep0.bin").read_bytes(),
        "fw_cfg1_bulk": (FW_DIR / "cfg1_bulk.bin").read_bytes(),
        "fw_cfg2_ep0":  (FW_DIR / "cfg2_ep0.bin").read_bytes(),
    }

    # Per-chip cfg2 variants.
    chips = []  # (jedec, name, sector_sym, chip_sym)
    per_chip_blobs: dict[str, bytes] = {}
    for jedec in TARGET_JEDECS:
        cp, sector, chip_erase = cfg2_variants(jedec)
        suf = f"{jedec:06x}"
        s_sym, c_sym = f"fw_cfg2_sector_{suf}", f"fw_cfg2_chip_{suf}"
        per_chip_blobs[s_sym] = sector
        per_chip_blobs[c_sym] = chip_erase
        chips.append((jedec, cp.name, s_sym, c_sym))

    out: list[str] = []
    out.append("/* Generated by gen_blob.py — do not edit. */")
    out.append(f"/* Board: {BOARD}  chips: "
               + ", ".join(f"0x{j:06x}({n})" for j, n, _, _ in chips) + " */")
    out.append("#ifndef FIRMWARE_BLOB_H")
    out.append("#define FIRMWARE_BLOB_H\n")
    out.append("#define INGENIC_VID   0xA108")
    out.append(f"#define BOOT_PID      0x{board.usb_pid:04X}")
    out.append(f"#define GINFO_ADDR    0x{board.ginfo_addr:08X}u")
    out.append(f"#define SPL_ADDR      0x{board.spl_addr:08X}u")
    out.append(f"#define STAGE2_ADDR   0x{board.stage2_addr:08X}u")
    out.append(f"#define D2I_LEN       0x{board.d2i_len:X}u")
    out.append(f"#define FLASH_OPS_NOR 0x{FLASH_OPS_NOR:08X}u\n")

    for name, data in shared.items():
        emit_array(out, name, data)
    for name, data in per_chip_blobs.items():
        emit_array(out, name, data)

    # Runtime chip table: live JEDEC -> matching cfg2 payloads.
    out.append("struct nor_chip {")
    out.append("    unsigned jedec;")
    out.append("    const char *name;")
    out.append("    const unsigned char *cfg2_sector; unsigned cfg2_sector_len;")
    out.append("    const unsigned char *cfg2_chip;   unsigned cfg2_chip_len;")
    out.append("};")
    out.append("static const struct nor_chip nor_chips[] = {")
    for jedec, name, s_sym, c_sym in chips:
        out.append(f'    {{ 0x{jedec:06x}u, "{name}", '
                   f"{s_sym}, {s_sym}_len, {c_sym}, {c_sym}_len }},")
    out.append("};")
    out.append(f"static const int nor_chips_count = {len(chips)};\n")
    out.append("#endif /* FIRMWARE_BLOB_H */")

    dest = Path(__file__).resolve().parent / "firmware_blob.h"
    dest.write_text("\n".join(out) + "\n")
    total = sum(len(b) for b in shared.values()) + sum(len(b) for b in per_chip_blobs.values())
    print(f"wrote {dest} ({len(chips)} chips, {total} bytes embedded)")
    return 0


def _has(name: str) -> bool:
    try:
        chip_by_name(name)
        return True
    except KeyError:
        return False


if __name__ == "__main__":
    raise SystemExit(main())
